version: "3"
services:
  dev:
    build:
      context: ./
      args:
        #// Update 'VARIANT' to pick a .NET Core version: 2.1, 3.1
        "VARIANT": "3.1"
        #// Options
        "INSTALL_NODE": "true"
        "NODE_VERSION": "lts/*"
        "INSTALL_AZURE_CLI": "false"
        # For Linux, Change the permission by specifying UID / GID.
        #"USER_UID": "1000"
        #"USER_GID": "1000"
    tty: true
    volumes: 
      - ..:/workspaces/examples-dotcore-webapi
    working_dir: /workspaces/examples-dotcore-webapi
